apiVersion : apps/v1
kind: Deployment
metadata:
  name: "demodfakscluster-3ee8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demodfakscluster-3ee8"
  template:
    metadata:
      labels:
        app: "demodfakscluster-3ee8"
    spec:
      containers:
        - name: "demodfakscluster-3ee8"
          image: "azuredfcontainerreg.azurecr.io/demodfakscluster"
          ports:
          - containerPort: 80